### PR TITLE
Replaced Nythendra's sounds with a real human voice.

### PR DESCRIPTION
**Pull request by Znuff**
Testing out real human voice sounds for boss abilities instead of text-to-speech ones.

If the reception is good, I could have the other bosses done, too.

### CODE REVIEW

**Comment by sehra** [comment]
I'm not against using real voices, but for a project like this it wouldn't be practical in the long run compared to TTS for a few reasons.
- Overhead: Have to prepare texts, send them off for recording and wait for results
- Cost: A professional voice over isn't free (Erika Lee recorded these, $5 per 100 words) so every minor text change would either have to be postponed for next major batch or incur extra costs
- Uniformity: I'd prefer if all sounds sounded the same, easy for a one-off job but would lock you to a certain voice actor and studio setup for future work

A better option would be some plugin system to pick which voice pack to use.

**Comment by Znuff** [comment]
You don't really change Voice Overs very often. Delaying them one week into expansion wouldn't be a big issue in my book.

I'm not concerned about the overhead. Takes a few hours, sure, but so does TTS. 

Personally I'm not concerned about Uniformity at all. I would actually prefer different voice actors per each raid/boss, makes things more interesting.

I can make my own fork and maintain that, not a big issue, tough it would be less than ideal.

**Comment by funkydude** [comment]
I'm going to change how the API works so that separate packs are viable.

**Comment by sehra** [comment]
> I'm not concerned about the overhead. Takes a few hours, sure, but so does TTS.

The overhead of TTS is very low. My workflow right now is to edit the text file with spells (this is the major part), then run a small program that takes the file, calls the speech API to write a wave file for each spell, then convert that to ogg.

**Pull request closed without merging**
